name: Boletify CD - Publish Android

on:
  push:
    branches:
      - deployment

jobs:
  publish-android:
    name: Publish Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v2