name: Boletify CD - Publish Android

on: [push]

jobs:
  publish-android:
    name: Publish Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v2
      - name: Install flutter
        uses: subosito/flutter-action@v1
      - name: Get packages
        run: flutter pub get
      - name: Generate keystore
        run: echo $KEY_JKS | base64 -d > android/app/key.jks
        env:
          KEY_JKS: ${{ secrets.KEYSTORE_JKS_B64 }}
      - name: Release compilation
        run: flutter build appbundle --release --build-name v1.0.2 --build-number 1
        env:
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PATH: key.jks
      - name: Publish Google Play (Internal)
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.ebgapps.boletify
          track: internal
          releaseFile: build/app/outputs/bundle/release/app-release.aab
      - name: Create new git version tag
        run: echo "::set-env name=NEXT_GIT_TAG::'v1.0.2+1'"
      - name: Update git version tag
        run: git tag $NEXT_GIT_TAG
      - name: Push git tag
        run: git push origin $NEXT_GIT_TAG