name: Boletify CI - Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 12.x
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: 2.2.3
      - run: flutter pub get
      - run: flutter analyze .

      - name: Generate keystore
        run: echo $KEY_JKS | base64 -d > android/app/key.jks
        env:
          KEY_JKS: ${{ secrets.KEYSTORE_JKS_B64 }}

      - name: Build APK
        run: flutter build apk
        env:
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PATH: key.jks

      - uses: actions/upload-artifact@v1
        with:
          path: build/app/outputs/apk/release/app-release.apk