name: Boletify CI - Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 12.x
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: 2.2.3
      - run: flutter doctor -v
      - run: flutter pub get
      - run: flutter analyze .

      - name: Build APK
        run: flutter build apk --debug --scan

      - uses: actions/upload-artifact@v1
        with:
          name: debug-apk
          path: build/app/outputs/apk/debug/app-debug.apk